---
deployment:
  tasks:
    - export DEPLOY_PATH=/home1/rudrarmq/findseniorsliving.thedemoonline.site
    - /bin/cp -R * $DEPLOY_PATH
    - cd $DEPLOY_PATH
    - php artisan migrate
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan optimize:clear
